export const commonTerms = [
  'Aparatología',
  'Limpieza Facial',
  'Toxina Botulínica',
  'Ácido Hialurónico',
  'Peeling Químico',
  'Depilación Láser',
  'Masaje Relajante',
  'Drenaje Linfático',
  'Microneedling',
  'Plasma Rico en Plaquetas',
  'Hidratación Profunda',
  'Rejuvenecimiento Facial',
  'Control de Acné',
  'Tratamiento Corporal',
  'Cavitación',
  'Radiofrecuencia',
  'Carboxiterapia',
  'Presoterapia',
  'Lipoláser',
  'Blanqueamiento Dental',
  'Rinomodelación',
  'Perfilado de Labios',
  'Aumento de Pómulos',
  'Hilos Tensores',
  'Bichectomía',
  'Valoración Médica',
  'Control Post-Tratamiento',
  'Sutura',
  'Anestesia Tópica',
  'Insumos Médicos',
  'Agujas 30G',
  'Jeringa 1cc',
  'Guantes Nitrilo',
  'Tapabocas',
  'Alcohol Antiséptico',
  'Gasa Estéril',
  'Algodón',
  'Gel Conductor',
  'Vitamina C',
  'Serum Antiedad',
  'Protector Solar'
];
